# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10
  
[[main]]
  name = "Highlights"
  url = "#highlights"
  weight = 20

[[main]]
  name = "Publications"
  url = "#publications"
  weight = 30

[[main]]
  name = "Experience"
  url = "#experience"
  weight = 40

[[main]]
  name = "Volunteer Work and Open Source"
  url = "#volunteer-work-and-open-source"
  weight = 50

[[main]]
  name = "Blog"
  url = "#blog"
  weight = 60

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 70

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/media/resume.pdf` and uncomment the lines below.
[[main]]
    name = "CV"
    url = "https://drive.google.com/file/d/16o515O3ImbqEOkSYOsx72Qan89u8Mjsj/view?usp=sharing"
    weight = 80
